### PR TITLE
Classroom and User page crash #56 fixed

### LINKED ISSUE #56: Classroom and User page crash
Steps to reproduce -
1.Start the server
2.Go to `http://127.0.0.1:8080/dashboard/classrooms`
3.Click on edit to edit any one the class
4.Now click on any one of the student in the left hand side search student box (this will shift student to the right hand side box).
5.Now click save
The server will crash . It will give error like this in the terminal .

`FATAL ERROR, uncaught exception 'classroomResponse.students.map is not a function'
TypeError: classroomResponse.students.map is not a function
    at /Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/api/controller/classrooms.js:465:55
    at result (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:401:11)
    at ClientSession.endSession (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb-core/lib/sessions.js:129:41)
    at executeCallback (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:397:17)
    at handleCallback (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.next (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/operations/collection_ops.js:598:5)
    at result (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/mongodb/lib/utils.js:128:55)
[nodemon] app crashed - waiting for file changes before starting...`

on Restarting the server , the server will start but on going to `http://127.0.0.1:8080/dashboard/users?lang=en` following error occurs -

screenshot 2019-03-04 at 1 04 19 pm

Similarly for classroom page 

TypeError: /Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/dashboard/views/classrooms.ejs:101
    99|                                           <td>
    100|                                               <% if(data.classrooms[i].students.length > 0) { %>
 >> 101|                                                   <a title="View Students" href="users?role=student&classid=<%- data.classrooms[i].students.join(',') %>"><span class="student-icon"></span></a>
    102|                                               <% } else { %>
    103|                                                   <a title="View Students" style="pointer-events: none;"><span class="student-icon"style="opacity: 0.4;"></span></a>
    104|                                               <% } %>

data.classrooms[i].students.join is not a function
    at eval (eval at compile (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/ejs/lib/ejs.js:592:12), <anonymous>:234:45)
    at returnedFn (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/ejs/lib/ejs.js:623:17)
    at tryHandleCache (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/ejs/lib/ejs.js:480:10)
    at View.render (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/express/lib/response.js:1008:7)
    at ServerResponse.res.render (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/node_modules/express-flash/lib/express-flash.js:29:16)
    at Request._callback (/Users/ashishaggarwal/Desktop/stuff/sugar/server/sugarizer-server/dashboard/controller/classrooms.js:55:8)

screenshot 2019-03-04 at 1 05 19 pm

This is removed after removing all the data present in the database  .

### PR DESCRIPTION
**Pull request by ashish0910**
Fixed #56 

screenshot 2019-03-04 at 3 38 33 pm

Student count increased 

screenshot 2019-03-04 at 3 46 55 pm

### CODE REVIEW

File: dashboard/controller/classrooms.js [hunk 1]
```diff
@@ -133,7 +133,12 @@ exports.editClassroom = function(req, res) {
 
 			// validate
 			req.body.name = req.body.name.trim();
-            req.body.students = req.body.students || [];
+			req.body.students = req.body.students || [];
+			
+			if (isString(req.body.students)) {
+				req.body.students = [req.body.students]
+			}
```
Comment (tarunsinghal92) [inline dashboard/controller/classrooms.js]: @ashish0910 Did you figure out why is it coming out to be a string?

**Comment by ashish0910** [comment]
@tarunsinghal92 in case of student count being one the api returns a single student id in form of string  but in case of student count greater than one it returns an array , so the #56 occurs only in case of student count being one so in order to solve that we converted it into an array .
